spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/data_local?reWriteBatchedInserts=true
    username: ${POSTGRESQL_USER:root}
    password: ${POSTGRESQL_PASSWORD:root}
  jpa:
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        id.new_generator_mappings: true
        generate_statistics: false
        jdbc:
          time_zone: UTC
          lob.non_contextual_creation: true
          batch_size: 50
          batch_versioned_data: true
        cache:
          use_second_level_cache: false
          region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        bytecode:
          provider: cglib
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    contexts: dev
